id: myflow
namespace: quickstart

inputs:
  - id: kestra_logo
    type: STRING
    defaults: https://avatars.githubusercontent.com/u/59033362?v=4

  - id: discord_webhook_url
    type: STRING
    defaults: https://discord.com/api/webhooks............. (get from your discord)
tasks:
  - id: python_script
    type: io.kestra.plugin.scripts.python.Commands
    namespaceFiles:
      enabled: true
    beforeCommands:
      - python3 -m venv .venv
      - . .venv/bin/activate
      - pip install -r scripts/requirements.txt
    commands:
      - python scripts/api_example.py

  - id: output_gh_stars
    type: io.kestra.plugin.core.log.Log
    message: "Number of stars : {{ outputs.python_script.vars.gh_stars }}"
  - id: send_notification
    type: io.kestra.plugin.notifications.discord.DiscordExecution
    avatarUrl: "{{inputs.kestra_logo}}"
    content: "Total of Github Stars: {{outputs.python_script.vars.gh_stars}}"
    username: kestra
    url: "{{inputs.discord_webhook_url}}"
triggers:
  - id: hour_trigger
    type: io.kestra.plugin.core.trigger.Schedule
    cron: 0 * * * *
